### ISSUE TITLE
Create a Google sheet script to export Worksheet2 as JSON

### ISSUE THREAD

**Issue by joshuaellinger** [COVID19Tracking/covid-publishing-api#13]
In Elliot's data entry repo, create a script that posts content as JSON to an endpoint in the API.

[Documented here b/c it is needed to support API development]

**Comment by joshuaellinger** [comment]
This replaces Issue #1.  

I'm planning to do two things:
    1. capture a static copy of the data and add it as a unit test for the API.
    2. Work with Elliot to set it up so he can run a test push upon request.

Is there anything else you want it to do at this point?

**Comment by zachlipton** [comment]
Just to get this someplace other than Slack:

The very mediocre incomplete version of the Apps Script (slurp up data from Worksheet 2 and post to a url) is attached to my copy of the spreadsheet at https://docs.google.com/spreadsheets/d/178b3lMSgzCBtZCxIqBJ8OmnQ9Nm4rWFe3OubnmPsIYg/edit#gid=2335020

I left a copy of the script in a gist in case there are access issues: https://gist.github.com/zachlipton/ce55a1b865d969a4f37c7bd45338c5d9

**Comment by joshuaellinger** [comment]
This is done.  Code is in data_entry repo.
