### ISSUE TITLE
Basic Flask E2E test using pytest

### ISSUE THREAD

**Issue by julia326** [COVID19Tracking/covid-publishing-api#15]
Our template didn't come with any tests - it'd be great to have a simple test case for running the app, hitting http://127.0.0.1:5000/api/v1/test/ and making sure it doesn't crash.

**Comment by joshuaellinger** [comment]
Done.  Assigning to Alex to confirm that CircleCI works

**Comment by joshuaellinger** [comment]
The flask app will not run without a DB.

So to make this simple test run, we need to:
   1. have a DB we can attach to.
   2. make a version of the .env file with the config information.
   3. start the flask app.
   4. run pytest.

**Comment by zachlipton** [comment]
Fixed in #17
