### ISSUE TITLE
[minor] convert notify_webook to annotation

### ISSUE THREAD

**Issue by space-buzzer** [COVID19Tracking/covid-publishing-api#150]
https://github.com/COVID19Tracking/covid-publishing-api/pull/149#issuecomment-694508063

**Comment by zachlipton** [comment]
Related to this, I'm realizing that we only call `notify_webhook` when we publish a new batch, but not on edits (data or state metadata). This made sense when publishing a new batch was always a separate operation, but now it's not. To avoid delays with edits going live, we should call it after edits too.

**Comment by zachlipton** [comment]
I was tired of the public API build not updating after edits and making the diffs confusing, so I did this in #162.
