### ISSUE TITLE
Extend toy POST request to take some data and write to the DB

### ISSUE THREAD

**Issue by julia326** [COVID19Tracking/covid-publishing-api#21]
(though need to fill out some SQLAlchemy models first)

**Comment by zachlipton** [comment]
Now that the models are in place, I can do a toy version of this quickly if that's useful or it can wait for the deserializer in #42 and this task can simply consist of "hand this data to the deserializer and stuff what comes back into the DB."

**Comment by julia326** [comment]
This has been fixed in #46, #48, and #49
