### ISSUE TITLE
SQLAlchemy models for DB schema

### ISSUE THREAD

**Issue by julia326** [COVID19Tracking/covid-publishing-api#3]
(but need to finalize data dictionary/set of spreadsheet columns first)

**Comment by joshuaellinger** [comment]
Talked to Elliot and Michal today.

The core data tabs are complete and ready to be turned into a schema.  I will cross validate against the actual sheet content later tonight.

**Comment by joshuaellinger** [comment]
https://docs.google.com/spreadsheets/d/13Lb_qJXwgtx5ySeXf_XyZkod9VAxEPGb3rmj8KUMQ8o/edit#gid=0

**Comment by julia326** [comment]
Partially addressed by #29

**Comment by julia326** [comment]
Marking this one closed, we will necessarily update some SQLAlchemy models as we go but an MVP of this is done
