### ISSUE TITLE
Script to backfill data from the spreadsheet to the DB

### ISSUE THREAD

**Issue by julia326** [COVID19Tracking/covid-publishing-api#35]
This script needs to be idempotent, in case we need to run it more than once.

**Comment by joshuaellinger** [comment]
That's what data convert is designed to provide.  

Julia -- there are a three ways I see to do this:
   1. have data_convert write to the DB directly (if and only-if it is empty)
   2. have data_convert run a series of posts against the API (one per day)
   3. like #2 but move data convert over to Google Sheets.

If we take #1, I suggest that we give data_convert its own login credentials so we can lock production against it but I do not recommend this approach.

Both #2 and #3 require support in the API for posting history which complicate it a bit but they have three advantages.  1. They would create a robust test that the API works against most of the variation that exists in the data.  2. The API can enforce that backfill only works up until a certain date.  3. You can run back-fill from any machine.

**Comment by julia326** [comment]
This one's done
