### ISSUE TITLE
Public API endpoints

### ISSUE THREAD

**Issue by zachlipton** [COVID19Tracking/covid-publishing-api#47]
We need three endpoints that basically mirror the existing public API to get data out of the DB.

Draft API specs are at https://studio-ws.apicur.io/sharing/9aef82b7-4132-4603-add0-39cf27415dae#tag/public, but it's pretty much "do what the public API does" along with the option to pass `?preview=true` to request preview data.

**Comment by julia326** [comment]
Endpoints we currently have from PR #52 :
- states/info
- states/daily

Need:
- us/daily

Also need:
- preview mode for all of these

**Comment by julia326** [comment]
Fixed by #52 and #62 . Going to open a separate issue for preview mode, to distinguish from the original set of MVP endpoints.
