### ISSUE TITLE
Double publish handling

### ISSUE THREAD

**Issue by zachlipton** [COVID19Tracking/covid-publishing-api#51]
Today's little double publish incident makes me realize we need a way to handle double publish situations such that:

- They don't happen accidentally. If there's already been a daily push for the day, there shouldn't be a second one 
- There's some sort of mechanism to quickly correct errors with a replacement push. I'm thinking this should involve knocking the last push back into the preview state (unpublishing it) and doing a new push on top of it, but would want to check with the data entry team for what makes sense to them

**Comment by julia326** [comment]
Also done!
