### ISSUE TITLE
Data validation—Include state name in errors

### ISSUE THREAD

**Issue by zachlipton** [COVID19Tracking/covid-publishing-api#94]
Data validation errors (e.g. a string in a numeric column) during a push currently produce hard-to-read errors. At a minimum, it would help to prominently indicate the state causing the error in the error message, to help the data entry team know what row to check for anomalies. 

There's a generic 500 server error handler in `app/__init__.py` that may be helpful in implementing this, and `test_push_with_validation_error()` is an example of the sort of validation error that comes up when invalid data is pushed.

**Comment by julia326** [comment]
This is fixed, along with some other improved error messaging
